sudo: false
language: ruby
rvm:
- 2.1.5
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- npm install
script:
- bundle exec rake travis_lint
- bundle exec rubocop -D
- bundle exec rake haml_lint
- bundle exec rake scss_lint
- bundle exec rake jscs
- bundle exec rake jshint
deploy:
  provider: heroku
  api_key:
    secure: TWB+vmlxnr8JHk8YXRrWTSyzpSA+GxsfGEnb26DpNcwseZu/4ph+Drl/T5k9AFbCBmDQPNkVBqd7gwyVhU+Jj2RiIw/uiCOvP7XBt5b+876NrGYW1AV3UhL744sGgCzDqNI2zw0y6uzk8MsPxwBNEEXMrWQPVdsTh/n5Xlny3zM=
  app:
    secure: FPE3iQgmDjOpV/NZcY4Cs0Z8r0rfNhkY1Fckclq0t/DtLklh8w8kV7tvnmlk14kJGJviNc2QRzilPFIzCD/SpquwBQu9SMhLOL4ln8Q7Xhi6gMjdpkclaOtY7zUG4sqjCqDSLvqJNvEp9IvZU3zG6+a6BMfteNLS5vJVU/NsC9Y=
